def build(bld):
    obj = bld.create_ns3_program('vanet_simulation', ['core', 'network', 'mobility', 'wifi', 'wave', 'internet', 'applications', 'flow-monitor'])
    obj.source = 'vanet_simulation.cc'